language: node_js
dist: xenial
node_js: lts/*
sudo: true

# limit the Travis 'build on push' feature to master branch only
branches:
  only:
   - master

install:
  - yarn install

script:
  - yarn lint

notifications:
  email:
    on_success: never
